=== dongpo/cargo-port-map/schemas/ports.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "ports",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string"
      },
      "name": {
        "type": [
          "string",
          "null"
        ]
      },
      "flag": {
        "type": [
          "string",
          "null"
        ]
      },
      "longitude": {
        "type": "number",
        "minimum": -180,
        "maximum": 180
      },
      "latitude": {
        "type": "number",
        "minimum": -90,
        "maximum": 90
      },
      "anchorage_id": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "required": [
      "id",
      "name",
      "flag",
      "longitude",
      "latitude",
      "anchorage_id"
    ],
    "additionalProperties": false
  }
}

=== dongpo/cargo-port-map/public/data/ports.json
[{"id":"alb-durres","name":null,"flag":"ALB","longitude":19.39959052577096,"latitude":41.254273149588066,"anchorage_id":"134fdcc1"},{"id":"are-abudhabi","name":"ABU DHABI","flag":"ARE","longitude":54.36021449053437,"latitude":24.535559852186392,"anchorage_id":"3e5e66b3"},{"id":"are-ajman","name":"AJMAN","flag":"ARE","longitude":55.454943244638926,"latitude":25.4267052297669,"anchorage_id":"3e5f5799"},{"id":"are-dubai","name":"DUBAI","flag":"ARE","longitude":55.259503524447126,"latitude":25.27624452341921,"anchorage_id":"3e5f4479"},{"id":"are-fujairah","name":"FUJAIRAH","flag":"ARE","longitude":56.58641991614923,"latitude":25.213311738009097,"anchorage_id":"3ef46023"},{"id":"are-jebelali","name":"JEBEL ALI","flag":"ARE","longitude":55.046615196720055,"latitude":25.029872558822024,"anchorage_id":"3e5f1161"},{"id":"are-khalifa","name":"KHALIFA","flag":"ARE","longitude":54.671002111805045,"latitude":24.82892882901852,"anchorage_id":"3e5efb0b"},{"id":"are-khorfakkan","name":"KHOR FAKKAN","flag":"ARE","longitude":56.597101413521905,"latitude":25.398533706792296,"anchorage_id":"3ef4685d"},{"id":"are-minasaqr","name":"MINA SAQR","flag":"ARE","longitude":56.00069269186633,"latitude":25.98351163227465,"anchorage_id":"3ef668c7"},{"id":"are-portrashid","name":"PORT RASHID","flag":"ARE","longitude":55.28715273953805,"latitude":25.272624527278875,"anchorage_id":"3e5f4367"},{"id":"are-sharjah","name":"SHARJAH","flag":"ARE","longitude":55.26259213953006,"latitude":25.4174674826895,"anchorage_id":"3e5f4ef3"},{"id":"are-ummalqaywayn","name":"UMM AL QAYWAYN","flag":"ARE","longitude":55.582465347910365,"latitude":25.590073131103576,"anchorage_id":"3ef5fde1"},{"id":"are-zakumfield","name":"ZAKUM FIELD","flag":"ARE","longitude":53.7129341392139,"latitude":24.90560595145313,"anchorage_id":"3e5c6d17"},{"id":"arg-arroyoseco","name":"ARROYO SECO","flag":"ARG","longitude":-60.47683790327197,"latitude":-33.138232666347704,"anchorage_id":"95b70c11"},{"id":"arg-bahiablanca","name":null,"flag":"ARG","longitude":-61.533574270744964,"latitude":-39.31228737940768,"anchorage_id":"95f2c597"},{"id":"arg-buenosaires","name":"BUENOS AIRES","flag":"ARG","longitude":-57.87927260914362,"latitude":-34.713153652312236,"anchorage_id":"95a31dad"},{"id":"arg-escobar","name":null,"flag":"ARG","longitude":-58.76036026772592,"latitude":-34.24141856578671,"anchorage_id":"95bb67a1"},{"id":"arg-sanlorenzo","name":"SAN LORENZO","flag":"ARG","longitude":-60.6999426109308,"latitude":-32.801818639984766,"anchorage_id":"95b650e9"},{"id":"aus-abbotpoint","name":null,"flag":"AUS","longitude":148.08423088397748,"latitude":-19.85700517702085,"anchorage_id":"6bd79489"},{"id":"aus-auntl","name":null,"flag":"AUS","longitude":151.70351565506158,"latitude":-33.18798482423439,"anchorage_id":"6b731fff"},{"id":"aus-bunbury","name":null,"flag":"AUS","longitude":115.56432839475528,"latitude":-33.23596562332629,"anchorage_id":"2a2e06ad"},{"id":"aus-dampier","name":null,"flag":"AUS","longitude":116.68114332753981,"latitude":-20.374080421865624,"anchorage_id":"2c09d921"},{"id":"aus-darwin","name":null,"flag":"AUS","longitude":130.70751628149193,"latitude":-12.316354353915262,"anchorage_id":"2cc0f403"},{"id":"aus-esperanceaus","name":null,"flag":"AUS","longitude":121.93876983212634,"latitude":-33.88724768864212,"anchorage_id":"2a5b4103"},{"id":"aus-fremantle","name":"FREMANTLE","flag":"AUS","longitude":115.71258735921398,"latitude":-32.01777571356257,"anchorage_id":"2a32a6d9"},{"id":"aus-geelong","name":null,"flag":"AUS","longitude":144.90720630259202,"latitude":-37.97191788584238,"anchorage_id":"6ad67b25"},{"id":"aus-geraldton","name":null,"flag":"AUS","longitude":114.49176581182081,"latitude":-28.72130701117079,"anchorage_id":"2bda37bd"},{"id":"aus-gladstone","name":null,"flag":"AUS","longitude":151.52168374564192,"latitude":-23.796062129181358,"anchorage_id":"6be9c531"},{"id":"aus-haypoint","name":null,"flag":"AUS","longitude":149.64094850927162,"latitude":-21.190103038067736,"anchorage_id":"6bdbe327"},{"id":"aus-kwinana","name":null,"flag":"AUS","longitude":115.69555816174221,"latitude":-32.168516240221784,"anchorage_id":"2a329e4f"},{"id":"aus-milnerbay","name":"MILNER BAY","flag":"AUS","longitude":136.3895407931544,"latitude":-13.862968042805928,"anchorage_id":"69e4883b"},{"id":"aus-newcastle","name":"NEWCASTLE","flag":"AUS","longitude":151.78496316734112,"latitude":-32.89215516563473,"anchorage_id":"6b7314a5"},{"id":"aus-porthedland","name":null,"flag":"AUS","longitude":118.56657229644307,"latitude":-20.06489786246207,"anchorage_id":"2c0aa99b"},{"id":"aus-portkembla","name":null,"flag":"AUS","longitude":151.00324370642556,"latitude":-34.36413570835664,"anchorage_id":"6b1320ff"},{"id":"aus-weipa","name":null,"flag":"AUS","longitude":141.61650595093803,"latitude":-12.927074902139116,"anchorage_id":"69bdedc1"},{"id":"bel-antwerp","name":"ANTWERP","flag":"BEL","longitude":4.2513254967104945,"latitude":51.35208961766227,"anchorage_id":"47c4749d"},{"id":"bel-zeebrugge","name":"ZEEBRUGGE","flag":"BEL","longitude":3.181090621725631,"latitude":51.35561607133933,"anchorage_id":"47c4a97d"},{"id":"ben-cotonou","name":"COTONOU","flag":"BEN","longitude":2.5025631787635176,"latitude":6.255623825110041,"anchorage_id":"103cada1"},{"id":"bgd-chittagong","name":"CHITTAGONG","flag":"BGD","longitude":91.79549997575332,"latitude":22.094655685201605,"anchorage_id":"30ace253"},{"id":"bgr-burgas","name":"BURGAS","flag":"BGR","longitude":27.589471531107566,"latitude":42.49444386840649,"anchorage_id":"40a6be37"},{"id":"bgr-varna","name":"VARNA","flag":"BGR","longitude":27.965658232710766,"latitude":43.15073499178536,"anchorage_id":"40a45059"},{"id":"bhr-sitrah","name":"SITRAH","flag":"BHR","longitude":50.779904523859614,"latitude":26.17896994391778,"anchorage_id":"3e490235"},{"id":"bhs-inaguaislands","name":"INAGUA ISLANDS","flag":"BHS","longitude":-73.65084404331702,"latitude":21.0501299974007,"anchorage_id":"8eca7d55"},{"id":"bra-bra-325","name":"BRA-325","flag":"BRA","longitude":-40.94029969691862,"latitude":-21.773844969315626,"anchorage_id":"00bef4dd"},{"id":"bra-fortaleza","name":"FORTALEZA","flag":"BRA","longitude":-38.41456258400241,"latitude":-3.6453468163658895,"anchorage_id":"07c73959"},{"id":"bra-ilhaguaiba","name":"ILHA GUAIBA","flag":"BRA","longitude":-44.03479885676185,"latitude":-23.0136277568041,"anchorage_id":"009c6b9f"},{"id":"bra-imbituba","name":"IMBITUBA","flag":"BRA","longitude":-48.616293345612654,"latitude":-28.21009552261032,"anchorage_id":"9526c9df"},{"id":"bra-itacoatiara","name":null,"flag":"BRA","longitude":-58.392425811830016,"latitude":-3.183012767256595,"anchorage_id":"926f5549"},{"id":"bra-itaguai","name":"ITAGUAI","flag":"BRA","longitude":-44.022424143760645,"latitude":-23.189148056139626,"anchorage_id":"009c66a1"},{"id":"bra-itajai","name":"ITAJAI","flag":"BRA","longitude":-48.53079046985728,"latitude":-26.900041730142362,"anchorage_id":"94d8c64f"},{"id":"bra-itaqui","name":"ITAQUI","flag":"BRA","longitude":-44.37770955996494,"latitude":-2.552851157224066,"anchorage_id":"07f6886d"},{"id":"bra-paranagua","name":"PARANAGUA","flag":"BRA","longitude":-48.390968541932104,"latitude":-25.508043515348756,"anchorage_id":"94dbbd51"},{"id":"bra-portocel","name":"PORTOCEL","flag":"BRA","longitude":-39.99460332553372,"latitude":-19.85667190019663,"anchorage_id":"00b7df9d"},{"id":"bra-portodoacu","name":"PORTO DO ACU","flag":"BRA","longitude":-40.95097357148113,"latitude":-21.849346106170916,"anchorage_id":"00be5fd1"},{"id":"bra-recife","name":"RECIFE","flag":"BRA","longitude":-34.83244595755294,"latitude":-8.077986918729778,"anchorage_id":"07ab2227"},{"id":"bra-riodejaneiro","name":"RIO DE JANEIRO","flag":"BRA","longitude":-43.16289748272575,"latitude":-23.042092619896938,"anchorage_id":"009a2b59"},{"id":"bra-riogrande","name":"RIO GRANDE","flag":"BRA","longitude":-52.086597434091686,"latitude":-32.16175692818206,"anchorage_id":"951183e9"},{"id":"bra-santana","name":"SANTANA","flag":"BRA","longitude":-51.098462478789635,"latitude":-0.06048275347297444,"anchorage_id":"929e1bff"},{"id":"bra-santos","name":"SANTOS","flag":"BRA","longitude":-46.173239970194295,"latitude":-24.092067346177604,"anchorage_id":"94d202df"},{"id":"bra-saoluis","name":"SAO LUIS","flag":"BRA","longitude":-44.29272000996068,"latitude":-2.411495032631783,"anchorage_id":"07f6f3b1"},{"id":"bra-ubu","name":"UBU","flag":"BRA","longitude":-40.52562519802013,"latitude":-20.770061837125446,"anchorage_id":"00b8fbd9"},{"id":"bra-vitoria","name":"VITORIA","flag":"BRA","longitude":-40.14836734204262,"latitude":-20.389687999819994,"anchorage_id":"00b811e3"},{"id":"brn-muara","name":"MUARA","flag":"BRN","longitude":115.09152494580849,"latitude":5.085186862681291,"anchorage_id":"3222fb2d"},{"id":"can-baiecomeau","name":"BAIE COMEAU","flag":"CAN","longitude":-68.10204598985703,"latitude":49.24163828123088,"anchorage_id":"4c93f7d7"},{"id":"can-becancour","name":"BECANCOUR","flag":"CAN","longitude":-72.37924067642285,"latitude":46.400613130246754,"anchorage_id":"4cc7bf5b"},{"id":"can-cacouna","name":"CACOUNA","flag":"CAN","longitude":-69.51389926946608,"latitude":47.9271816542707,"anchorage_id":"4cbe3bd1"},{"id":"can-can-152","name":"CAN-152","flag":"CAN","longitude":-73.91502064123726,"latitude":45.32208660605287,"anchorage_id":"4cc94131"},{"id":"can-can-161","name":"CAN-161","flag":"CAN","longitude":-79.85154630008074,"latitude":44.750333655123,"anchorage_id":"4d2adb35"},{"id":"can-can-206","name":"CAN-206","flag":"CAN","longitude":-82.48268077360046,"latitude":42.74086209602462,"anchorage_id":"88256dd1"},{"id":"can-can-221","name":"CAN-221","flag":"CAN","longitude":-73.93098510333787,"latitude":45.29684635952054,"anchorage_id":"4cc943fd"},{"id":"can-can-244","name":"CAN-244","flag":"CAN","longitude":-75.6828221888885,"latitude":44.586342410672245,"anchorage_id":"4ccd0f77"},{"id":"can-can-291","name":"CAN-291","flag":"CAN","longitude":-123.63025183703094,"latitude":49.01841114903388,"anchorage_id":"5488aaf1"},{"id":"can-can-35"
